### ISSUE TITLE
sbt-jib build the entire project instead of the last layer

### ISSUE THREAD

**Issue by dylandoamaral** [schmitch/sbt-jib#51] opened 2020-06-21 10:42 UTC
Hello there,

First of all, thank you for this amazing plugin :D.

I would like to know if it is normal that the command jibDockerBuild always takes a lot of time (100 sec) even if I only change a string inside my code.

If my understanding of jib is enough, jib should only update the last layer of my application and take less time to build the image, right ? I just would like to know if I am wrong or if I did something the bad way :/

The command I run:

`sbt compile jibDockerBuild`

**Comment by pschichtel** [comment] 2021-04-19 20:51
I think this is caused by the jib caches being in a temp folder, see #7

**Comment by pschichtel** [comment] 2021-04-20 23:00
@schmitch this one should also be fixed with #59

**Closed** 2021-04-21 07:17 UTC
